services:
  - type: web
    name: drying-records
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drying-records-db
          property: connectionString
      - key: SECRET_KEY
        value: your-super-secret-key
